<script setup>
import { onMounted, ref } from "vue";
import clientsService from "@/services/clients.service";
const clients = ref([]); const showForm = ref(false); const loading = ref(true); const error = ref("");
const form = ref({ name: "", industry: "", manager: "", status: "نشط", campaigns: 0, revenue: "0 ر.س" });
async function load() { try { clients.value = await clientsService.getAll(); } catch (e) { error.value = e.message; } finally { loading.value = false; } }
async function create() { const client = await clientsService.create(form.value); clients.value.push(client); form.value = { name: "", industry: "", manager: "", status: "نشط", campaigns: 0, revenue: "0 ر.س" }; showForm.value = false; }
onMounted(load);
</script>
<template><section class="space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-blue-600">إدارة العلاقات</p><h1 class="mt-1 text-2xl font-bold sm:text-3xl">العملاء</h1><p class="mt-2 text-slate-500">إدارة جميع العملاء ومتابعة أداء حساباتهم.</p></div><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700" @click="showForm = !showForm">+ إضافة عميل</button></div>
<form v-if="showForm" class="grid gap-4 rounded-2xl border border-blue-100 bg-blue-50 p-5 sm:grid-cols-4" @submit.prevent="create"><input v-model="form.name" required placeholder="اسم العميل" class="rounded-xl border-0 px-4 py-3"/><input v-model="form.industry" placeholder="القطاع" class="rounded-xl border-0 px-4 py-3"/><input v-model="form.manager" placeholder="مدير الحساب" class="rounded-xl border-0 px-4 py-3"/><button class="rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white">حفظ العميل</button></form>
<p v-if="error" class="rounded-xl bg-red-50 p-4 text-red-700">{{ error }} — شغّل الخادم عبر <code>npm run server</code></p><div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="w-full min-w-[760px] text-right text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">اسم العميل</th><th>القطاع</th><th>الحملات</th><th>الإيرادات</th><th>مدير الحساب</th><th>الحالة</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="p-8 text-center text-slate-500">جاري تحميل العملاء...</td></tr><tr v-for="client in clients" v-else :key="client.id" class="border-t border-slate-100"><td class="p-4 font-semibold">{{ client.name }}</td><td>{{ client.industry }}</td><td>{{ client.campaigns }}</td><td>{{ client.revenue }}</td><td>{{ client.manager }}</td><td><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{{ client.status }}</span></td></tr></tbody></table></div></section></template>
