<script setup>
import { onMounted, ref } from "vue";
import leadsService from "@/services/leads.service";
const leads = ref([]); const showForm = ref(false); const loading = ref(true); const error = ref(""); const form = ref({ name: "", company: "", phone: "", source: "Google Ads", value: "0 ر.س", status: "جديد" });
async function load() { try { leads.value = await leadsService.getAll(); } catch (e) { error.value = e.message; } finally { loading.value = false; } }
async function create() { const lead = await leadsService.create(form.value); leads.value.push(lead); form.value = { name: "", company: "", phone: "", source: "Google Ads", value: "0 ر.س", status: "جديد" }; showForm.value = false; }
onMounted(load);
</script>
<template><section class="space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-blue-600">إدارة المبيعات</p><h1 class="mt-1 text-2xl font-bold sm:text-3xl">العملاء المحتملون</h1><p class="mt-2 text-slate-500">تابع الفرص الجديدة وحوّلها إلى عملاء.</p></div><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700" @click="showForm = !showForm">+ إضافة عميل محتمل</button></div><form v-if="showForm" class="grid gap-4 rounded-2xl border border-blue-100 bg-blue-50 p-5 sm:grid-cols-4" @submit.prevent="create"><input v-model="form.name" required placeholder="اسم العميل المحتمل" class="rounded-xl border-0 px-4 py-3"/><input v-model="form.company" placeholder="الشركة" class="rounded-xl border-0 px-4 py-3"/><input v-model="form.phone" placeholder="رقم الهاتف" class="rounded-xl border-0 px-4 py-3"/><button class="rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white">حفظ العميل المحتمل</button></form><p v-if="error" class="rounded-xl bg-red-50 p-4 text-red-700">{{ error }} — شغّل الخادم عبر <code>npm run server</code></p><div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="w-full min-w-[760px] text-right text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">الاسم</th><th>الشركة</th><th>الهاتف</th><th>المصدر</th><th>القيمة المتوقعة</th><th>الحالة</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="p-8 text-center text-slate-500">جاري التحميل...</td></tr><tr v-for="lead in leads" v-else :key="lead.id" class="border-t border-slate-100"><td class="p-4 font-semibold">{{ lead.name }}</td><td>{{ lead.company }}</td><td>{{ lead.phone }}</td><td>{{ lead.source }}</td><td>{{ lead.value }}</td><td><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{{ lead.status }}</span></td></tr></tbody></table></div></section></template>
